name: Docker_Runner_Workflow

on:
  workflow_dispatch:

env:
  RUNNER_VERSION: 2.294.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker-github-runner.

    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3.0.2

      - name: Build
        run: |
          docker build --build-arg RUNNER_VERSION=${{ env.RUNNER_VERSION }} -t ${{ env.CONTAINER_IMAGE_REPOSITORY }}/docker-github-runner:${{ env.RUNNER_VERSION }}
      
      - name: "Vulnerability scan container image with Trivy"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.CONTAINER_IMAGE_REPOSITORY }}/docker-github-runner:${{ env.RUNNER_VERSION }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute container repository name
        run: |
          echo "CONTAINER_IMAGE_REPOSITORY=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Build and push container image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.CONTAINER_IMAGE_REPOSITORY }}/docker-github-runner:${{ env.RUNNER_VERSION }}